### PR TITLE
Fix machine orientation bug

### PR DESCRIPTION
**Pull request by FantasyTeddy**
This should fix Issue #76

### CODE REVIEW

**Comment by joekaiser** [comment]
Thanks for this. I recall there was a reason it was done like I had it, but I don't remember off hand. You probably even saw my todo in there.

When I get home I will look at this closer. I think it is good, but I want to check it with some of my non-pushed branches for testing. 

Thanks for another potential fix :)

**Comment by joekaiser** [comment]
I remember why I did it now. For some reason the Icon rendering messes up. Notice how a lot of the items no longer show the "Front" side. I just never looked into why.

image

**Comment by FantasyTeddy** [comment]
You are right, that's an issue...
I did some digging, because I was wondering why a normal Minecraft furnace works correctly even though its `getIcon` and `onBlockPlacedBy` function are basically implemented the same way as your machines.
It turns out that they manually set the block metadata to 3 when rendering a furnace, dispenser or dropper as an item.

One solution I can think of would be to change the metadata association: a value of `0` or `1` would no longer belong to a block facing up or down, but to the side visible as an item.
The disadvantage of this approach would be that it messes up the appearance of existing machines.

**Comment by joekaiser** [comment]
Closing this because it is now invalid with 1.8.9. Thanks for the effort though :)

**Pull request closed without merging**
