### PR TITLE
Upgrade to Minecraft version 1.11.2

### PR DESCRIPTION
**Pull request by FantasyTeddy**
Summary:
I tried to upgrade to Minecraft version 1.11.2. As far as I can tell, everything works like in the previous version (but I could have forgotten something...).
Unfortunately the assets needed to be converted to lowercase filenames to work with this version.

### CODE REVIEW

**Comment by joekaiser** [comment]
woah! Thanks! I have been wanting to do this.  I'll take a look this week and fix anything quirks I can find.

**Comment by FantasyTeddy** [comment]
Great! I hope you're not mad at me for giving it a try.
I was also thinking of doing the 1.12 transition, what do you think?

**Comment by joekaiser** [comment]
I won't stop you, but don't hurry on it. Im pretty busy these days and my spare time to go over PRs is limited

**Comment by FantasyTeddy** [comment]
Alright. I'll leave it as a surprise, whether I'll do it or not ;)

**Pull request closed without merging**
