### PR TITLE
1.3.2

### PR DESCRIPTION
**Pull request by p455w0rd**
Fix Achievements and such for mods the rely on ItemPickupEvent to trigger events in their code

### CODE REVIEW

**Comment by joekaiser** [comment]
this branch (and subsequently 1.7.10) is locked. I will make sure to include this in the 1.9 branch

**Comment by joekaiser** [comment]
Actually, in 1.9 the FML bus is deprecated so no changes are needed. thanks though :)

**Comment by p455w0rd** [comment]
this change was for the 1.7.10 version :/

**Comment by joekaiser** [comment]
It doesn't defeat the point at all. Legitimate game breaking bugs are one thing, but I decided a while ago to lock 1.7.10 version for anything but that. I only have a few hours a month to devote to this mod, and my time is best used making this great for 1.9.

Sorry man :(

**Comment by joekaiser** [comment]
Think of it this way. had Forge not deprecated the FML bus, i could have just merged this fix right into the 1.9 branch. I think it was just a bad coincidence that it wasn't needed.

**Comment by p455w0rd** [comment]
All good..I comlpletely understand =] Thanks for the mod and helping me understand MC code a bit more!

**Comment by joekaiser** [comment]
Anytime! Part of the reason I wanted to open this mod was to share what I learned :) Let me know if you have any questions.

Also, anything in the issue list that has the "bug" label or "help wanted" is free to grab ;)

**Pull request closed without merging**
